# Generated by Django 2.2.3 on 2019-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
