# Generated by Django 2.2.3 on 2019-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_auto_20190727_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
